//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnouncementsTbl
    {
        public int A_Id { get; set; }
        public string A_Title { get; set; }
        public string A_Desc { get; set; }
        public byte[] A_Pic { get; set; }
        public Nullable<System.DateTime> A_Date { get; set; }
    }
}
