//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoaRehabTbl
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Desc { get; set; }
        public string Addr { get; set; }
        public string Mission { get; set; }
        public string Vision { get; set; }
        public string Emails { get; set; }
        public string Ph_No { get; set; }
        public string Statutes { get; set; }
    }
}
