//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InmatesTbl
    {
        public int In_Id { get; set; }
        public string In_Name { get; set; }
        public string Gender { get; set; }
        public int Proj_Id { get; set; }
    
        public virtual ProjectsTbl ProjectsTbl { get; set; }
    }
}
