//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsTbl
    {
        public int N_Id { get; set; }
        public string N_Title { get; set; }
        public string N_Desc { get; set; }
        public byte[] N_Pic { get; set; }
        public Nullable<System.DateTime> N_Date { get; set; }
    }
}
