//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PicturesTbl
    {
        public int Pic_Id { get; set; }
        public string Pic_Name { get; set; }
        public string Pic_Path { get; set; }
    }
}
