//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileTbl
    {
        public int P_Id { get; set; }
        public string P_Name { get; set; }
        public string P_Pic { get; set; }
        public string P_Desc { get; set; }
        public string P_Designation { get; set; }
    }
}
