//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectsTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectsTbl()
        {
            this.InmatesTbls = new HashSet<InmatesTbl>();
        }
    
        public int Proj_Id { get; set; }
        public string Proj_Title { get; set; }
        public string Proj_Desc { get; set; }
        public byte[] Proj_Pic { get; set; }
        public string Proj_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InmatesTbl> InmatesTbls { get; set; }
    }
}
