//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RtiTbl
    {
        public int Id { get; set; }
        public string RTI { get; set; }
        public string PIO { get; set; }
        public string APIO { get; set; }
    }
}
